# ======================================================================
# ArgoCD Application: framely-stage
#
# Environment:
# - Stage (Local KIND / Pre-Production)
#
# Purpose:
# - Connect ArgoCD with Kubernetes manifests stored in Git
# - Continuously sync the desired state from Git to the cluster
#
# This application:
# - Watches kubernetes/stage directory
# - Deploys all Framely services into framely-stage namespace
# - Uses GitOps principles (Git = source of truth)
# ======================================================================

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: framely-stage
  namespace: argocd                # ArgoCD control-plane namespace
spec:
  # --------------------------------------------------------------------
  # ArgoCD Project this application belongs to
  # --------------------------------------------------------------------
  project: framely

  # --------------------------------------------------------------------
  # Source: Git repository containing Kubernetes manifests
  # --------------------------------------------------------------------
  source:
    repoURL: https://github.com/<YOUR_GITHUB_USERNAME>/framely
    targetRevision: stage          # Track the 'stage' branch only
    path: kubernetes/stage          # GitOps manifests location

    # Kustomize is used to manage image tags and namespaces
    kustomize:
      # No extra configuration needed for now
      # Image tags are updated by Jenkins in kustomization.yaml files
      {}

  # --------------------------------------------------------------------
  # Destination: Kubernetes cluster and namespace
  # --------------------------------------------------------------------
  destination:
    server: https://kubernetes.default.svc
    namespace: framely-stage       # All resources deploy here

  # --------------------------------------------------------------------
  # Sync Policy
  # --------------------------------------------------------------------
  syncPolicy:
    automated:
      prune: true                  # Remove resources deleted from Git
      selfHeal: true               # Revert manual cluster changes

    syncOptions:
      - CreateNamespace=true       # Auto-create namespace if missing
      - ApplyOutOfSyncOnly=true    # Apply only when drift is detected

  # --------------------------------------------------------------------
  # Optional: Revision history
  # --------------------------------------------------------------------
  revisionHistoryLimit: 5
